/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@9.1.1'.
 * 
 * (c) Kontent.ai
 *  
 * -------------------------------------------------------------------------------
 * 
 * Project: Join a gym [NextJS Template]
 * Environment: Production
 * Id: 2c45647a-1ddb-0169-0a7e-5783f31fe85d
 * 
 * -------------------------------------------------------------------------------
 */

export * from "./collections/default-collection.generated.ts"
export * from "./languages/english-uk-language.generated.ts"
export * from "./snippets/seo-metadata.generated.ts"
export * from "./snippets/snippet.generated.ts"
export * from "./system/collections.generated.ts"
export * from "./system/elements.generated.ts"
export * from "./system/languages.generated.ts"
export * from "./system/main.system.generated.ts"
export * from "./system/snippets.generated.ts"
export * from "./system/taxonomies.generated.ts"
export * from "./system/types.generated.ts"
export * from "./system/workflows.generated.ts"
export * from "./taxonomies/article-tags.generated.ts"
export * from "./types/article.generated.ts"
export * from "./types/banner.generated.ts"
export * from "./types/faq.generated.ts"
export * from "./types/membership-plan.generated.ts"
export * from "./types/page.generated.ts"
export * from "./types/person.generated.ts"
export * from "./workflows/default-workflow.generated.ts"
