/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@9.1.1'.
 * 
 * (c) Kontent.ai
 *  
 * -------------------------------------------------------------------------------
 * 
 * Project: Karma Health Demo
 * Environment: Karma Health - IvanK
 * Id: ed845612-1d5a-018a-110d-81ee1eee30bf
 * 
 * -------------------------------------------------------------------------------
 */

import type { LanguageCodenames } from "../system/languages.generated"

/*
 * Type representing codename of 'English (en-US)' language
 */
export type EnglishEnUSLanguageCodename = keyof Pick<Record<LanguageCodenames, null>, "default">

/*
 * Typeguard for codename of 'English (en-US)' language
 */
export function isEnglishEnUSLanguageCodename(value: string | undefined | null): value is EnglishEnUSLanguageCodename {
  return typeof value === "string" && value === ("default" satisfies EnglishEnUSLanguageCodename)
}
