/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@9.1.1'.
 * 
 * (c) Kontent.ai
 *  
 * -------------------------------------------------------------------------------
 * 
 * Project: Join a gym [NextJS Template]
 * Environment: Production
 * Id: 2c45647a-1ddb-0169-0a7e-5783f31fe85d
 * 
 * -------------------------------------------------------------------------------
 */

import type { LanguageCodenames } from "../system/languages.generated.ts"

/*
 * Type representing codename of 'English (UK)' language
 */
export type EnglishUKLanguageCodename = keyof Pick<Record<LanguageCodenames, null>, "en_gb">

/*
 * Typeguard for codename of 'English (UK)' language
 */
export function isEnglishUKLanguageCodename(value: string | undefined | null): value is EnglishUKLanguageCodename {
  return typeof value === "string" && value === ("en_gb" satisfies EnglishUKLanguageCodename)
}
