/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@9.1.1'.
 * 
 * (c) Kontent.ai
 *  
 * -------------------------------------------------------------------------------
 * 
 * Project: Karma Health Demo
 * Environment: Karma Health - IvanK
 * Id: ed845612-1d5a-018a-110d-81ee1eee30bf
 * 
 * -------------------------------------------------------------------------------
 */

import type { LanguageCodenames } from "../system/languages.generated"

/*
 * Type representing codename of 'German (de-DE)' language
 */
export type GermanDeDELanguageCodename = keyof Pick<Record<LanguageCodenames, null>, "de-DE">

/*
 * Typeguard for codename of 'German (de-DE)' language
 */
export function isGermanDeDELanguageCodename(value: string | undefined | null): value is GermanDeDELanguageCodename {
  return typeof value === "string" && value === ("de-DE" satisfies GermanDeDELanguageCodename)
}
