/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@9.1.1'.
 * 
 * (c) Kontent.ai
 *  
 * -------------------------------------------------------------------------------
 * 
 * Project: Karma Health Demo
 * Environment: Karma Health - IvanK
 * Id: ed845612-1d5a-018a-110d-81ee1eee30bf
 * 
 * -------------------------------------------------------------------------------
 */

import type { LanguageCodenames } from "../system/languages.generated"

/*
 * Type representing codename of 'Spanish (es-ES)' language
 */
export type SpanishEsESLanguageCodename = keyof Pick<Record<LanguageCodenames, null>, "es-ES">

/*
 * Typeguard for codename of 'Spanish (es-ES)' language
 */
export function isSpanishEsESLanguageCodename(value: string | undefined | null): value is SpanishEsESLanguageCodename {
  return typeof value === "string" && value === ("es-ES" satisfies SpanishEsESLanguageCodename)
}
