/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@9.1.1'.
 * 
 * (c) Kontent.ai
 *  
 * -------------------------------------------------------------------------------
 * 
 * Project: Join a gym [NextJS Template]
 * Environment: Production
 * Id: 2c45647a-1ddb-0169-0a7e-5783f31fe85d
 * 
 * -------------------------------------------------------------------------------
 */

/*
 * Array of all element codenames
 */
export const elementCodenames = [
  "headline",
  "subheadline",
  "header_image",
  "content",
  "slug",
  "seo_metadata__meta_title",
  "seo_metadata__meta_description",
  "seo_metadata__og_image",
  "subpages",
  "name",
  "tagline",
  "monthly_price",
  "features",
  "cta_label",
  "full_name",
  "role",
  "bio",
  "photo",
  "email",
  "title",
  "perex",
  "body",
  "author",
  "published_date",
  "tags",
  "snippet__text_field",
  "question",
  "answer",
  "image",
] as const

/*
 * Type representing all element codenames
 */
export type ElementCodenames = (typeof elementCodenames)[number]

/*
 * Typeguard for element codename
 */
export function isElementCodename(value: string | undefined | null): value is ElementCodenames {
  return typeof value === "string" && (elementCodenames as readonly string[]).includes(value)
}
