/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@9.1.1'.
 * 
 * (c) Kontent.ai
 *  
 * -------------------------------------------------------------------------------
 * 
 * Project: Join a gym [NextJS Template]
 * Environment: Production
 * Id: 2c45647a-1ddb-0169-0a7e-5783f31fe85d
 * 
 * -------------------------------------------------------------------------------
 */

/*
 * Array of all language codenames
 */
export const languageCodenames = ["en_gb"] as const

/*
 * Type representing all language codenames
 */
export type LanguageCodenames = (typeof languageCodenames)[number]

/*
 * Typeguard for language codename
 */
export function isLanguageCodename(value: string | undefined | null): value is LanguageCodenames {
  return typeof value === "string" && (languageCodenames as readonly string[]).includes(value)
}
