/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@9.1.1'.
 * 
 * (c) Kontent.ai
 *  
 * -------------------------------------------------------------------------------
 * 
 * Project: Join a gym [NextJS Template]
 * Environment: Production
 * Id: 2c45647a-1ddb-0169-0a7e-5783f31fe85d
 * 
 * -------------------------------------------------------------------------------
 */

import type { IDeliveryClient } from "@kontent-ai/delivery-sdk"
import type { CollectionCodenames } from "./collections.generated.ts"
import type { ElementCodenames } from "./elements.generated.ts"
import type { LanguageCodenames } from "./languages.generated.ts"
import type { TaxonomyCodenames } from "./taxonomies.generated.ts"
import type { CoreType, TypeCodenames } from "./types.generated.ts"
import type { WorkflowCodenames, WorkflowStepCodenames } from "./workflows.generated.ts"

/*
 * Core types for 'IDeliveryClient'
 */
export type CoreClientTypes = {
  readonly collectionCodenames: CollectionCodenames
  readonly contentItemType: CoreType
  readonly contentTypeCodenames: TypeCodenames
  readonly elementCodenames: ElementCodenames
  readonly languageCodenames: LanguageCodenames
  readonly taxonomyCodenames: TaxonomyCodenames
  readonly workflowCodenames: WorkflowCodenames
  readonly workflowStepCodenames: WorkflowStepCodenames
}

/*
 * Typed delivery client. Use this instead of 'IDeliveryClient'
 */
export type CoreDeliveryClient = IDeliveryClient<CoreClientTypes>
