/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@9.1.1'.
 * 
 * (c) Kontent.ai
 *  
 * -------------------------------------------------------------------------------
 * 
 * Project: Join a gym [NextJS Template]
 * Environment: Production
 * Id: 2c45647a-1ddb-0169-0a7e-5783f31fe85d
 * 
 * -------------------------------------------------------------------------------
 */

/*
 * Array of all snippet codenames
 */
export const snippetCodenames = ["seo_metadata", "snippet"] as const

/*
 * Type representing all snippet codenames
 */
export type SnippetCodenames = (typeof snippetCodenames)[number]

/*
 * Typeguard for snippet codename
 */
export function isSnippetCodename(value: string | undefined | null): value is SnippetCodenames {
  return typeof value === "string" && (snippetCodenames as readonly string[]).includes(value)
}
