/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@9.1.1'.
 * 
 * (c) Kontent.ai
 *  
 * -------------------------------------------------------------------------------
 * 
 * Project: Join a gym [NextJS Template]
 * Environment: Production
 * Id: 2c45647a-1ddb-0169-0a7e-5783f31fe85d
 * 
 * -------------------------------------------------------------------------------
 */

import type { ArticleType } from "../types/article.generated.ts"
import type { BannerType } from "../types/banner.generated.ts"
import type { FaqType } from "../types/faq.generated.ts"
import type { MembershipPlanType } from "../types/membership-plan.generated.ts"
import type { PageType } from "../types/page.generated.ts"
import type { PersonType } from "../types/person.generated.ts"

/*
 * Array of all type codenames
 */
export const typeCodenames = ["page", "membership_plan", "person", "article", "faq", "banner"] as const

/*
 * Type representing all type codenames
 */
export type TypeCodenames = (typeof typeCodenames)[number]

/*
 * Typeguard for type codename
 */
export function isTypeCodename(value: string | undefined | null): value is TypeCodenames {
  return typeof value === "string" && (typeCodenames as readonly string[]).includes(value)
}

/*
 * Core content type with narrowed types. Use this instead of'IContentItem' for increased type safety.
 */
export type CoreType = PageType | MembershipPlanType | PersonType | ArticleType | FaqType | BannerType

/*
 * Type mapping for codename & type. Can be used for type safe access to type based on the codename of type.
 */
export type CodenameTypeMapping = {
  readonly page: PageType
  readonly membership_plan: MembershipPlanType
  readonly person: PersonType
  readonly article: ArticleType
  readonly faq: FaqType
  readonly banner: BannerType
}

/*
 * Helper type that returns type based on the codename of type.
 */
export type CodenameTypeMapper<TTypeCodename extends TypeCodenames> = TTypeCodename extends keyof CodenameTypeMapping
  ? CodenameTypeMapping[TTypeCodename]
  : CoreType
