/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@9.1.1'.
 * 
 * (c) Kontent.ai
 *  
 * -------------------------------------------------------------------------------
 * 
 * Project: Join a gym [NextJS Template]
 * Environment: Production
 * Id: 2c45647a-1ddb-0169-0a7e-5783f31fe85d
 * 
 * -------------------------------------------------------------------------------
 */

import type { TaxonomyCodenames } from "../system/taxonomies.generated.ts"

/*
 * Type representing codename of 'Article Tags' taxonomy
 */
export type ArticleTagsTaxonomyCodename = keyof Pick<Record<TaxonomyCodenames, null>, "article_tags">

/*
 * Typeguard for codename of 'Article Tags' taxonomy
 */
export function isArticleTagsTaxonomyCodename(value: string | undefined | null): value is ArticleTagsTaxonomyCodename {
  return typeof value === "string" && value === ("article_tags" satisfies ArticleTagsTaxonomyCodename)
}

/*
 * Array of all taxonomy term codenames
 */
export const articleTagsTaxonomyTermCodenames = ["news", "health___fitness", "membership"] as const

/*
 * Type representing all taxonomy term codenames
 */
export type ArticleTagsTaxonomyTermCodenames = (typeof articleTagsTaxonomyTermCodenames)[number]

/*
 * Typeguard for taxonomy term codename
 */
export function isArticleTagsTaxonomyTermCodename(
  value: string | undefined | null,
): value is ArticleTagsTaxonomyTermCodenames {
  return typeof value === "string" && (articleTagsTaxonomyTermCodenames as readonly string[]).includes(value)
}
