/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@9.1.1'.
 * 
 * (c) Kontent.ai
 *  
 * -------------------------------------------------------------------------------
 * 
 * Project: Karma Health Demo
 * Environment: Karma Health - IvanK
 * Id: ed845612-1d5a-018a-110d-81ee1eee30bf
 * 
 * -------------------------------------------------------------------------------
 */

import type { TaxonomyCodenames } from "../system/taxonomies.generated"

/*
 * Type representing codename of 'General Healthcare Topics' taxonomy
 */
export type GeneralHealthcareTopicsTaxonomyCodename = keyof Pick<
  Record<TaxonomyCodenames, null>,
  "general_healthcare_topics"
>

/*
 * Typeguard for codename of 'General Healthcare Topics' taxonomy
 */
export function isGeneralHealthcareTopicsTaxonomyCodename(
  value: string | undefined | null,
): value is GeneralHealthcareTopicsTaxonomyCodename {
  return (
    typeof value === "string" &&
    value === ("general_healthcare_topics" satisfies GeneralHealthcareTopicsTaxonomyCodename)
  )
}

/*
 * Array of all taxonomy term codenames
 */
export const generalHealthcareTopicsTaxonomyTermCodenames = [
  "healthcare_policy___regulations",
  "medical_research___innovations",
  "health___wellness",
  "preventative_care",
  "public_health",
] as const

/*
 * Type representing all taxonomy term codenames
 */
export type GeneralHealthcareTopicsTaxonomyTermCodenames = (typeof generalHealthcareTopicsTaxonomyTermCodenames)[number]

/*
 * Typeguard for taxonomy term codename
 */
export function isGeneralHealthcareTopicsTaxonomyTermCodename(
  value: string | undefined | null,
): value is GeneralHealthcareTopicsTaxonomyTermCodenames {
  return (
    typeof value === "string" && (generalHealthcareTopicsTaxonomyTermCodenames as readonly string[]).includes(value)
  )
}
