/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@9.1.1'.
 * 
 * (c) Kontent.ai
 *  
 * -------------------------------------------------------------------------------
 * 
 * Project: Join a gym [NextJS Template]
 * Environment: Production
 * Id: 2c45647a-1ddb-0169-0a7e-5783f31fe85d
 * 
 * -------------------------------------------------------------------------------
 */

import type { Elements, IContentItem } from "@kontent-ai/delivery-sdk"
import type { SEOMetadataSnippet } from "../snippets/seo-metadata.generated.ts"
import type { SnippetSnippet } from "../snippets/snippet.generated.ts"
import type { CollectionCodenames } from "../system/collections.generated.ts"
import type { LanguageCodenames } from "../system/languages.generated.ts"
import type { CoreType, TypeCodenames } from "../system/types.generated.ts"
import type { WorkflowCodenames, WorkflowStepCodenames } from "../system/workflows.generated.ts"
import type {
  ArticleTagsTaxonomyCodename,
  ArticleTagsTaxonomyTermCodenames,
} from "../taxonomies/article-tags.generated.ts"
import type { PersonType } from "../types/person.generated.ts"

/*
 * Type representing codename of 'Article' type
 */
export type ArticleTypeCodename = keyof Pick<Record<TypeCodenames, null>, "article">

/*
 * Typeguard for codename of 'Article' type
 */
export function isArticleTypeCodename(value: string | undefined | null): value is ArticleTypeCodename {
  return typeof value === "string" && value === ("article" satisfies ArticleTypeCodename)
}

/*
 * Article
 *
 * Id: 3ed4bf81-5ebc-4e7b-90ec-74f53ff6e1b9
 * Codename: article
 */
export type ArticleType = IContentItem<
  {
    /*
     * Title
     *
     * Codename: title
     * Id: 9b5e62fd-8593-40c2-9f6e-7b0b33748747
     * Type: text
     * Required: true
     */
    readonly title: Elements.TextElement

    /*
     * Perex
     *
     * Codename: perex
     * Id: f4a91a63-c485-4c67-a93a-029c5342c38b
     * Type: text
     * Required: false
     */
    readonly perex: Elements.TextElement

    /*
     * Body
     *
     * Codename: body
     * Id: e06f4634-095d-423c-ac9b-c668827adce5
     * Type: rich_text
     * Required: false
     */
    readonly body: Elements.RichTextElement<CoreType>

    /*
     * Author
     *
     * Codename: author
     * Id: b273f298-074e-4140-a452-87168ff9268d
     * Type: modular_content
     * Required: false
     * Allowed content types: person
     */
    readonly author: Elements.LinkedItemsElement<PersonType>

    /*
     * Published date
     *
     * Codename: published_date
     * Id: 506256f7-33e2-408e-96dd-b5d1848c2ac9
     * Type: date_time
     * Required: false
     */
    readonly published_date: Elements.DateTimeElement

    /*
     * Article Tags
     *
     * Codename: tags
     * Id: d4dcaf17-fad9-4c6d-9c91-9a4e1adb0c6b
     * Type: taxonomy
     * Required: false
     * Taxonomy: article_tags
     */
    readonly tags: Elements.TaxonomyElement<ArticleTagsTaxonomyTermCodenames, ArticleTagsTaxonomyCodename>

    /*
     * Slug
     *
     * Codename: slug
     * Id: 37ac96dd-d745-4f0d-8f2f-d4902cf135d1
     * Type: url_slug
     * Required: true
     */
    readonly slug: Elements.UrlSlugElement
  } & SEOMetadataSnippet &
    SnippetSnippet,
  ArticleTypeCodename,
  LanguageCodenames,
  CollectionCodenames,
  WorkflowCodenames,
  WorkflowStepCodenames
>

/*
 * Type representing all available element codenames for Article
 */
export type ArticleTypeElementCodenames =
  | "title"
  | "perex"
  | "body"
  | "author"
  | "published_date"
  | "tags"
  | "slug"
  | "seo_metadata__meta_title"
  | "seo_metadata__meta_description"
  | "seo_metadata__og_image"
  | "snippet__text_field"

/*
 * Type guard for Article
 *
 * Id: 3ed4bf81-5ebc-4e7b-90ec-74f53ff6e1b9
 * Codename: article
 */
export function isArticleType(item: IContentItem | undefined | null): item is ArticleType {
  return item?.system.type === ("article" satisfies ArticleTypeCodename)
}
