/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@9.1.1'.
 * 
 * (c) Kontent.ai
 *  
 * -------------------------------------------------------------------------------
 * 
 * Project: Join a gym [NextJS Template]
 * Environment: Production
 * Id: 2c45647a-1ddb-0169-0a7e-5783f31fe85d
 * 
 * -------------------------------------------------------------------------------
 */

import type { Elements, IContentItem } from "@kontent-ai/delivery-sdk"
import type { CollectionCodenames } from "../system/collections.generated.ts"
import type { LanguageCodenames } from "../system/languages.generated.ts"
import type { CoreType, TypeCodenames } from "../system/types.generated.ts"
import type { WorkflowCodenames, WorkflowStepCodenames } from "../system/workflows.generated.ts"

/*
 * Type representing codename of 'Banner' type
 */
export type BannerTypeCodename = keyof Pick<Record<TypeCodenames, null>, "banner">

/*
 * Typeguard for codename of 'Banner' type
 */
export function isBannerTypeCodename(value: string | undefined | null): value is BannerTypeCodename {
  return typeof value === "string" && value === ("banner" satisfies BannerTypeCodename)
}

/*
 * Banner
 *
 * Id: ea7d9fdd-ce6e-464a-8315-6e84ef2f6ef0
 * Codename: banner
 */
export type BannerType = IContentItem<
  {
    /*
     * Headline
     *
     * Codename: headline
     * Id: 4fdda533-cd41-4f22-b4df-e467d8dd8940
     * Type: text
     * Required: false
     */
    readonly headline: Elements.TextElement

    /*
     * Body
     *
     * Codename: body
     * Id: 909e34d8-fb22-475a-9982-34f8d40f415b
     * Type: rich_text
     * Required: false
     */
    readonly body: Elements.RichTextElement<CoreType>

    /*
     * Image
     *
     * Codename: image
     * Id: 86a6a327-d569-4d78-a081-1b1d314a4798
     * Type: asset
     * Required: false
     */
    readonly image: Elements.AssetsElement
  },
  BannerTypeCodename,
  LanguageCodenames,
  CollectionCodenames,
  WorkflowCodenames,
  WorkflowStepCodenames
>

/*
 * Type representing all available element codenames for Banner
 */
export type BannerTypeElementCodenames = "headline" | "body" | "image"

/*
 * Type guard for Banner
 *
 * Id: ea7d9fdd-ce6e-464a-8315-6e84ef2f6ef0
 * Codename: banner
 */
export function isBannerType(item: IContentItem | undefined | null): item is BannerType {
  return item?.system.type === ("banner" satisfies BannerTypeCodename)
}
