/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@9.1.1'.
 * 
 * (c) Kontent.ai
 *  
 * -------------------------------------------------------------------------------
 * 
 * Project: Join a gym [NextJS Template]
 * Environment: Production
 * Id: 2c45647a-1ddb-0169-0a7e-5783f31fe85d
 * 
 * -------------------------------------------------------------------------------
 */

import type { Elements, IContentItem } from "@kontent-ai/delivery-sdk"
import type { CollectionCodenames } from "../system/collections.generated.ts"
import type { LanguageCodenames } from "../system/languages.generated.ts"
import type { CoreType, TypeCodenames } from "../system/types.generated.ts"
import type { WorkflowCodenames, WorkflowStepCodenames } from "../system/workflows.generated.ts"

/*
 * Type representing codename of 'Faq' type
 */
export type FaqTypeCodename = keyof Pick<Record<TypeCodenames, null>, "faq">

/*
 * Typeguard for codename of 'Faq' type
 */
export function isFaqTypeCodename(value: string | undefined | null): value is FaqTypeCodename {
  return typeof value === "string" && value === ("faq" satisfies FaqTypeCodename)
}

/*
 * Faq
 *
 * Id: 1ab73760-a1ad-4a0b-9902-6db9876525f9
 * Codename: faq
 */
export type FaqType = IContentItem<
  {
    /*
     * Question
     *
     * Codename: question
     * Id: 0813c815-fd65-4b07-b7df-499bf758fb68
     * Type: text
     * Required: false
     */
    readonly question: Elements.TextElement

    /*
     * Answer
     *
     * Codename: answer
     * Id: 245c657c-646d-4c3c-9586-279ac0159c01
     * Type: rich_text
     * Required: false
     */
    readonly answer: Elements.RichTextElement<CoreType>
  },
  FaqTypeCodename,
  LanguageCodenames,
  CollectionCodenames,
  WorkflowCodenames,
  WorkflowStepCodenames
>

/*
 * Type representing all available element codenames for Faq
 */
export type FaqTypeElementCodenames = "question" | "answer"

/*
 * Type guard for Faq
 *
 * Id: 1ab73760-a1ad-4a0b-9902-6db9876525f9
 * Codename: faq
 */
export function isFaqType(item: IContentItem | undefined | null): item is FaqType {
  return item?.system.type === ("faq" satisfies FaqTypeCodename)
}
