/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@9.1.1'.
 * 
 * (c) Kontent.ai
 *  
 * -------------------------------------------------------------------------------
 * 
 * Project: Join a gym [NextJS Template]
 * Environment: Production
 * Id: 2c45647a-1ddb-0169-0a7e-5783f31fe85d
 * 
 * -------------------------------------------------------------------------------
 */

import type { Elements, IContentItem } from "@kontent-ai/delivery-sdk"
import type { SEOMetadataSnippet } from "../snippets/seo-metadata.generated.ts"
import type { CollectionCodenames } from "../system/collections.generated.ts"
import type { LanguageCodenames } from "../system/languages.generated.ts"
import type { CoreType, TypeCodenames } from "../system/types.generated.ts"
import type { WorkflowCodenames, WorkflowStepCodenames } from "../system/workflows.generated.ts"

/*
 * Type representing codename of 'Membership Plan' type
 */
export type MembershipPlanTypeCodename = keyof Pick<Record<TypeCodenames, null>, "membership_plan">

/*
 * Typeguard for codename of 'Membership Plan' type
 */
export function isMembershipPlanTypeCodename(value: string | undefined | null): value is MembershipPlanTypeCodename {
  return typeof value === "string" && value === ("membership_plan" satisfies MembershipPlanTypeCodename)
}

/*
 * Membership Plan
 *
 * Id: 9fd1f8fd-43b2-4d9c-8c40-0878fc16651e
 * Codename: membership_plan
 */
export type MembershipPlanType = IContentItem<
  {
    /*
     * Name
     *
     * Codename: name
     * Id: 0360c871-d04f-44b8-bbc5-1f778dfe901b
     * Type: text
     * Required: true
     * Guidelines: The plan name, e.g. Classic, Premium, Off-Peak.
     */
    readonly name: Elements.TextElement

    /*
     * Tagline
     *
     * Codename: tagline
     * Id: 1e0645f6-fd96-4dd9-a803-9709093b7490
     * Type: text
     * Required: false
     * Guidelines: Short selling line shown beneath the plan name.
     */
    readonly tagline: Elements.TextElement

    /*
     * Monthly price
     *
     * Codename: monthly_price
     * Id: 84849ab1-97f1-452a-a829-a0a0265db1b0
     * Type: number
     * Required: false
     * Guidelines: Price in local currency (GBP for UK).
     */
    readonly monthly_price: Elements.NumberElement

    /*
     * Features
     *
     * Codename: features
     * Id: e8d395b1-ee70-413c-b20e-a00662543f61
     * Type: rich_text
     * Required: false
     * Guidelines: Bullet list of what's included in this plan.
     */
    readonly features: Elements.RichTextElement<CoreType>

    /*
     * CTA label
     *
     * Codename: cta_label
     * Id: 713a7c5a-626b-4725-9052-7390867490b9
     * Type: text
     * Required: false
     * Guidelines: Button text for the join CTA, e.g. Join now.
     */
    readonly cta_label: Elements.TextElement
  } & SEOMetadataSnippet,
  MembershipPlanTypeCodename,
  LanguageCodenames,
  CollectionCodenames,
  WorkflowCodenames,
  WorkflowStepCodenames
>

/*
 * Type representing all available element codenames for Membership Plan
 */
export type MembershipPlanTypeElementCodenames =
  | "name"
  | "tagline"
  | "monthly_price"
  | "features"
  | "cta_label"
  | "seo_metadata__meta_title"
  | "seo_metadata__meta_description"
  | "seo_metadata__og_image"

/*
 * Type guard for Membership Plan
 *
 * Id: 9fd1f8fd-43b2-4d9c-8c40-0878fc16651e
 * Codename: membership_plan
 */
export function isMembershipPlanType(item: IContentItem | undefined | null): item is MembershipPlanType {
  return item?.system.type === ("membership_plan" satisfies MembershipPlanTypeCodename)
}
