/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@9.1.1'.
 * 
 * (c) Kontent.ai
 *  
 * -------------------------------------------------------------------------------
 * 
 * Project: Join a gym [NextJS Template]
 * Environment: Production
 * Id: 2c45647a-1ddb-0169-0a7e-5783f31fe85d
 * 
 * -------------------------------------------------------------------------------
 */

import type { Elements, IContentItem } from "@kontent-ai/delivery-sdk"
import type { SEOMetadataSnippet } from "../snippets/seo-metadata.generated.ts"
import type { CollectionCodenames } from "../system/collections.generated.ts"
import type { LanguageCodenames } from "../system/languages.generated.ts"
import type { CoreType, TypeCodenames } from "../system/types.generated.ts"
import type { WorkflowCodenames, WorkflowStepCodenames } from "../system/workflows.generated.ts"

/*
 * Type representing codename of 'Page' type
 */
export type PageTypeCodename = keyof Pick<Record<TypeCodenames, null>, "page">

/*
 * Typeguard for codename of 'Page' type
 */
export function isPageTypeCodename(value: string | undefined | null): value is PageTypeCodename {
  return typeof value === "string" && value === ("page" satisfies PageTypeCodename)
}

/*
 * Page
 *
 * Id: e6180d3c-243d-4b28-9384-4c79dfebe7b9
 * Codename: page
 */
export type PageType = IContentItem<
  {
    /*
     * Headline
     *
     * Codename: headline
     * Id: 7daab764-6e9d-4a0b-bc6e-1f231c8bce04
     * Type: text
     * Required: false
     * Guidelines: The main heading displayed in the page hero. Falls back to Title if empty.
     */
    readonly headline: Elements.TextElement

    /*
     * Subheadline
     *
     * Codename: subheadline
     * Id: 8e36443c-d454-47ad-baab-b065d4b894af
     * Type: text
     * Required: false
     * Guidelines: A short subtitle displayed below the headline in the page hero.
     */
    readonly subheadline: Elements.TextElement

    /*
     * Header image
     *
     * Codename: header_image
     * Id: 7d562acd-9031-4506-af34-ac78471f5f44
     * Type: asset
     * Required: false
     * Guidelines: Wide banner image displayed in the page hero. AI smart-cropped to fit.
     */
    readonly header_image: Elements.AssetsElement

    /*
     * Content
     *
     * Codename: content
     * Id: ebdef6b8-b264-4031-90d4-adadcf65aef1
     * Type: rich_text
     * Required: false
     * Guidelines: Main body content for the page.
     */
    readonly content: Elements.RichTextElement<CoreType>

    /*
     * Slug
     *
     * Codename: slug
     * Id: 06d44d2e-0fe0-4b98-a8b4-f1a38e4a31d7
     * Type: url_slug
     * Required: true
     * Guidelines: Auto-generated from the headline. Use lowercase, hyphens only.
     */
    readonly slug: Elements.UrlSlugElement

    /*
     * Subpages
     *
     * Codename: subpages
     * Id: 8dc17bf5-36ba-4436-9b96-bd236541572d
     * Type: subpages
     * Required: false
     * Allowed content types: page
     */
    readonly subpages: Elements.LinkedItemsElement<PageType>
  } & SEOMetadataSnippet,
  PageTypeCodename,
  LanguageCodenames,
  CollectionCodenames,
  WorkflowCodenames,
  WorkflowStepCodenames
>

/*
 * Type representing all available element codenames for Page
 */
export type PageTypeElementCodenames =
  | "headline"
  | "subheadline"
  | "header_image"
  | "content"
  | "slug"
  | "seo_metadata__meta_title"
  | "seo_metadata__meta_description"
  | "seo_metadata__og_image"
  | "subpages"

/*
 * Type guard for Page
 *
 * Id: e6180d3c-243d-4b28-9384-4c79dfebe7b9
 * Codename: page
 */
export function isPageType(item: IContentItem | undefined | null): item is PageType {
  return item?.system.type === ("page" satisfies PageTypeCodename)
}
