/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@9.1.1'.
 * 
 * (c) Kontent.ai
 *  
 * -------------------------------------------------------------------------------
 * 
 * Project: Join a gym [NextJS Template]
 * Environment: Production
 * Id: 2c45647a-1ddb-0169-0a7e-5783f31fe85d
 * 
 * -------------------------------------------------------------------------------
 */

import type { Elements, IContentItem } from "@kontent-ai/delivery-sdk"
import type { CollectionCodenames } from "../system/collections.generated.ts"
import type { LanguageCodenames } from "../system/languages.generated.ts"
import type { CoreType, TypeCodenames } from "../system/types.generated.ts"
import type { WorkflowCodenames, WorkflowStepCodenames } from "../system/workflows.generated.ts"

/*
 * Type representing codename of 'Person' type
 */
export type PersonTypeCodename = keyof Pick<Record<TypeCodenames, null>, "person">

/*
 * Typeguard for codename of 'Person' type
 */
export function isPersonTypeCodename(value: string | undefined | null): value is PersonTypeCodename {
  return typeof value === "string" && value === ("person" satisfies PersonTypeCodename)
}

/*
 * Person
 *
 * Id: 20f63e06-22e3-45f7-a9c6-f9e3fa821dd8
 * Codename: person
 */
export type PersonType = IContentItem<
  {
    /*
     * Full name
     *
     * Codename: full_name
     * Id: 41dce0a8-bd74-4165-a36c-6a5bd3379b08
     * Type: text
     * Required: true
     */
    readonly full_name: Elements.TextElement

    /*
     * Role
     *
     * Codename: role
     * Id: 9450de1c-dfc5-4cde-a558-c1ff94efeff4
     * Type: text
     * Required: false
     */
    readonly role: Elements.TextElement

    /*
     * Bio
     *
     * Codename: bio
     * Id: 8dbf7765-4fc9-44b9-bf19-c0d74b06b9d6
     * Type: rich_text
     * Required: false
     */
    readonly bio: Elements.RichTextElement<CoreType>

    /*
     * Photo
     *
     * Codename: photo
     * Id: 5e71b31f-8363-46e4-95b4-ff8b2f726e10
     * Type: asset
     * Required: false
     */
    readonly photo: Elements.AssetsElement

    /*
     * Email
     *
     * Codename: email
     * Id: 1471376a-a50d-41e1-b729-4b905733cc3d
     * Type: text
     * Required: false
     */
    readonly email: Elements.TextElement
  },
  PersonTypeCodename,
  LanguageCodenames,
  CollectionCodenames,
  WorkflowCodenames,
  WorkflowStepCodenames
>

/*
 * Type representing all available element codenames for Person
 */
export type PersonTypeElementCodenames = "full_name" | "role" | "bio" | "photo" | "email"

/*
 * Type guard for Person
 *
 * Id: 20f63e06-22e3-45f7-a9c6-f9e3fa821dd8
 * Codename: person
 */
export function isPersonType(item: IContentItem | undefined | null): item is PersonType {
  return item?.system.type === ("person" satisfies PersonTypeCodename)
}
