/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@9.1.1'.
 * 
 * (c) Kontent.ai
 *  
 * -------------------------------------------------------------------------------
 * 
 * Project: Karma Health Demo
 * Environment: Karma Health - IvanK
 * Id: ed845612-1d5a-018a-110d-81ee1eee30bf
 * 
 * -------------------------------------------------------------------------------
 */

import type { Elements, Snippet } from "@kontent-ai/delivery-sdk"
import type { SnippetCodenames } from "../system/snippets.generated"

/*
 * Type representing codename of 'Metadata' snippet
 */
export type MetadataSnippetCodename = keyof Pick<Record<SnippetCodenames, null>, "metadata">

/*
 * Typeguard for codename of 'Metadata' snippet
 */
export function isMetadataSnippetCodename(value: string | undefined | null): value is MetadataSnippetCodename {
  return typeof value === "string" && value === ("metadata" satisfies MetadataSnippetCodename)
}

/*
 * Metadata
 *
 * Id: 97c9abc7-223b-46a6-bf1d-061ca1db0d76
 * Codename: metadata
 */
export type MetadataSnippet = Snippet<
  MetadataSnippetElementCodenames,
  {
    /*
     * Meta Title
     *
     * Codename: metadata__title
     * Id: 6acb8e2f-3e36-4a9e-9da4-85691ea88ba8
     * Type: text
     * Required: false
     */
    readonly metadata__title: Elements.TextElement

    /*
     * Keywords
     *
     * Codename: metadata__keywords
     * Id: a84fd8ec-16f2-4ebe-9e77-59cd1fed1d49
     * Type: text
     * Required: false
     */
    readonly metadata__keywords: Elements.TextElement

    /*
     * Description
     *
     * Codename: metadata__description
     * Id: 2223c595-ac0e-4ea9-b767-67b47d19d6bc
     * Type: text
     * Required: false
     */
    readonly metadata__description: Elements.TextElement
  }
>

/*
 * Type representing all available element codenames for Metadata
 */
export type MetadataSnippetElementCodenames = "metadata__title" | "metadata__keywords" | "metadata__description"
