/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@9.1.1'.
 * 
 * (c) Kontent.ai
 *  
 * -------------------------------------------------------------------------------
 * 
 * Project: Join a gym [NextJS Template]
 * Environment: Production
 * Id: 2c45647a-1ddb-0169-0a7e-5783f31fe85d
 * 
 * -------------------------------------------------------------------------------
 */

import type { Elements, Snippet } from "@kontent-ai/delivery-sdk"
import type { SnippetCodenames } from "../system/snippets.generated.ts"

/*
 * Type representing codename of 'SEO Metadata' snippet
 */
export type SEOMetadataSnippetCodename = keyof Pick<Record<SnippetCodenames, null>, "seo_metadata">

/*
 * Typeguard for codename of 'SEO Metadata' snippet
 */
export function isSEOMetadataSnippetCodename(value: string | undefined | null): value is SEOMetadataSnippetCodename {
  return typeof value === "string" && value === ("seo_metadata" satisfies SEOMetadataSnippetCodename)
}

/*
 * SEO Metadata
 *
 * Id: 5e367a16-9a22-4c3e-a617-65bf423918b3
 * Codename: seo_metadata
 */
export type SEOMetadataSnippet = Snippet<
  SEOMetadataSnippetElementCodenames,
  {
    /*
     * Meta title
     *
     * Codename: seo_metadata__meta_title
     * Id: 3e40d0da-43f4-461a-9557-150b705687ac
     * Type: text
     * Required: false
     * Guidelines: Recommended: 50–60 characters. Defaults to the page title if left empty.
     */
    readonly seo_metadata__meta_title: Elements.TextElement

    /*
     * Meta description
     *
     * Codename: seo_metadata__meta_description
     * Id: f59d2276-7658-49bd-af65-09317ccc19d1
     * Type: text
     * Required: false
     * Guidelines: Recommended: 150–160 characters. Used in search engine results.
     */
    readonly seo_metadata__meta_description: Elements.TextElement

    /*
     * OG image
     *
     * Codename: seo_metadata__og_image
     * Id: 19d0fa77-461f-4334-8703-305be041043f
     * Type: asset
     * Required: false
     * Guidelines: Social sharing image. Recommended size: 1200×630px.
     */
    readonly seo_metadata__og_image: Elements.AssetsElement
  }
>

/*
 * Type representing all available element codenames for SEO Metadata
 */
export type SEOMetadataSnippetElementCodenames =
  | "seo_metadata__meta_title"
  | "seo_metadata__meta_description"
  | "seo_metadata__og_image"
