/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@9.1.1'.
 * 
 * (c) Kontent.ai
 *  
 * -------------------------------------------------------------------------------
 * 
 * Project: Join a gym [NextJS Template]
 * Environment: Production
 * Id: 2c45647a-1ddb-0169-0a7e-5783f31fe85d
 * 
 * -------------------------------------------------------------------------------
 */

import type { Elements, Snippet } from "@kontent-ai/delivery-sdk"
import type { SnippetCodenames } from "../system/snippets.generated.ts"

/*
 * Type representing codename of 'Snippet' snippet
 */
export type SnippetSnippetCodename = keyof Pick<Record<SnippetCodenames, null>, "snippet">

/*
 * Typeguard for codename of 'Snippet' snippet
 */
export function isSnippetSnippetCodename(value: string | undefined | null): value is SnippetSnippetCodename {
  return typeof value === "string" && value === ("snippet" satisfies SnippetSnippetCodename)
}

/*
 * Snippet
 *
 * Id: b101c105-d3f9-40ad-a341-c3eed67c937e
 * Codename: snippet
 */
export type SnippetSnippet = Snippet<
  SnippetSnippetElementCodenames,
  {
    /*
     * Text Field
     *
     * Codename: snippet__text_field
     * Id: ab0f29c3-f68d-4ad2-ab58-c4f698117f43
     * Type: text
     * Required: false
     */
    readonly snippet__text_field: Elements.TextElement
  }
>

/*
 * Type representing all available element codenames for Snippet
 */
export type SnippetSnippetElementCodenames = "snippet__text_field"
